explore_node:
  ros__parameters:
    use_sim_time: true
    robot_base_frame: "base_footprint"
    costmap_topic: "/map"
    costmap_updates_topic: "/map/map_updates"
    visualize: true
    planner_frequency: 0.33
    progress_timeout: 60.0
    return_to_init: false
    min_frontier_size: 0.25     
    potential_scale: 1.0        
    orientation_scale: 0.0 
    gain_scale: 2.0             
    transform_tolerance: 0.5     
